config/routes.rb
Station::Application.routes.draw do
  root 'home#index'

  get   '/about'    => 'home#about'
  match '/login'    => 'home#login', :via => [:get, :post]
  match '/register' => 'home#register', :via => [:get, :post]
  match '/logout'   => 'home#logout', :via => [:get, :post]

  get   '/auth/:provider/callback' => 'auth#callback'

  post '/tasks/:id/complete' => 'tasks#complete', :as => 'complete_task'
  post '/tasks/:id/pass'     => 'tasks#pass', :as => 'pass_task'

  resources :tasks
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  scope :pending, -> { where(:completed_at => nil).order(:updated_at => :asc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password :validations => false

  has_many :identities
  has_many :tasks

  validates_presence_of   :name
  validates_uniqueness_of :email, :if => :has_email?
  validates               :email, :email => true, :if => :has_email?

  strip_attributes :except => [:password, :password_confirmation]

  def has_email?
    self.email.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordInvalid, :with => :handle_validation_error

  helper_method :logged_in?, :current_user

  def alert(message, type=:info)
    flash[:notice] = message
    flash[:notice_type] = type
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user_checked ||= begin
      @current_user = session[:user_id] && User.find(session[:user_id])
      true
    end

    @current_user
  end

  def login_user(user)
    session[:user_id] = user.id
  end

  def logout_user
    session.delete(:user_id)
  end

  protected

  def handle_validation_error(error)
    alert(error.record.errors.full_messages.first, :error)
    redirect_to(root_path)
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def callback
    auth_hash     = request.env['omniauth.auth']
    identity_info = auth_hash.slice('provider', 'uid').symbolize_keys
    user_info     = auth_hash['info'].slice('name', 'email').symbolize_keys

    identity = Identity.find_by(identity_info)

    if identity.nil?
      identity = Identity.create!(identity_info)
    end

    user = identity.user

    if user.nil?
      user = User.find_by(:email => user_info[:email])
    end

    if user.nil?
      user = User.create!(user_info)
      alert("Thanks for joining, #{user.name}!", :success)
    else
      alert("Welcome back, #{user.name}!")
    end

    if identity.user.nil?
      identity.user = user
      identity.save!
    end

    login_user(user)
    redirect_to(root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login
    if request.post?
      user = User.find_by(:email => params[:email])

      if user.nil?
        alert('No user exists with that e-mail address.', :info)
        return redirect_to(login_path)
      end

      if !user.authenticate(params[:password])
        alert('That password is incorrect.', :error)
        return redirect_to(login_path)
      end

      login_user(user)
      alert("Welcome back, #{user.name}!", :success)
      redirect_to(root_path)
    end
  end

  def logout
    logout_user
    alert('See you next time.')
    redirect_to(root_path)
  end

  def register
    if request.post?
      user = User.create!({
        :name => params[:name],
        :email => params[:email],
        :password => params[:password],
        :password_confirmation => params[:password_confirmation]
      })

      login_user(user)
      alert("Thanks for registering, #{user.name}!", :success)
      redirect_to(root_path)
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = current_user.tasks.pending.first
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.create(task_params)

    if @task.save
      alert('Task saved successfully.')
      redirect_to(tasks_path)

    else
      alert('Error saving task.', :error)
      render(:action => 'new')
    end
  end

  def complete
    @task = Task.find(params[:id])
    @task.completed_at = Time.now
    @task.save!
    alert('Task completed.')
    redirect_to(tasks_path)
  end

  def pass
    @task = Task.find(params[:id])
    @task.touch
    alert('Procrastination successful :)')
    redirect_to(tasks_path)
  end

  private

  def task_params
    params.require(:task).permit(:description, :comments)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_identifier
    "#{params[:controller]}-#{params[:action]}"
  end

  def render_partial(name, data={})
    render(:partial => "partials/#{name}", :locals => data)
  end

  def nav_menu
    render_partial('nav_menu')
  end

  def nav_link(text, path)
    content_tag(:li, :class => current_page?(path) ? 'active' : nil) do
      link_to(text, path)
    end
  end

  def notice
    render_partial('notice', :type => flash[:notice_type], :message => flash[:notice])
  end

  def form_field(name, type=:text)
    render_partial('form_field', :field => name, :type => type)
  end

  def form_submit(text)
    render_partial('form_submit', :text => text)
  end
end

app/views/home/index.html.erb
<% if !logged_in? %>
  <p><%= link_to('Log in', login_path) %> to continue.</p>
<% else %>
  <p>
    <%= gravatar_image_tag(current_user.email) %>
    Welcome, <%= current_user.name %>!
  </p>
<% end %>

app/views/home/login.html.haml
= form_tag(login_path) do
  = form_field(:email)
  = form_field(:password, :password)
  = form_submit('Log in')

%p Or log in with:

%ul
  %li= link_to('Google', '/auth/google_oauth2')
  %li= link_to('Facebook', '/auth/facebook')
  %li= link_to('GitHub', '/auth/github')

%p
  Need to create an account?
  = link_to('Register', register_path)

app/views/home/register.html.haml
= form_tag(register_path) do
  = form_field(:name)
  = form_field(:email)
  = form_field(:password, :password)
  = form_field(:password_confirmation, :password)
  = form_submit('Register')

%p
  Already have an account?
  = link_to('Log in', login_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= APP_NAME
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = stylesheet_link_tag('application', :media => 'all', :'data-turbolinks-track' => true)
    = javascript_include_tag('vendor/modernizr')
    = csrf_meta_tags

  %body(data-page="#{page_identifier}")
    %header
      %h1= APP_NAME

    = notice

    %main
      = nav_menu
      %section#content= yield

    = javascript_include_tag('application', :'data-turbolinks-track' => true)

app/views/partials/_form_field.html.erb
<div class="field">
  <label for="<%= field %>"><%= String(field).humanize %></label>
  <input type="<%= type %>" name="<%= field %>" />
</div>

app/views/partials/_form_submit.html.erb
<div class="row">
  <div class="actions">
    <input type="submit" value="<%= text %>" />
  </div>
</div>

app/views/partials/_nav_menu.html.haml
%nav
  %ul
    = nav_link('Home', root_path)
    = nav_link('Next Task', tasks_path)
    = if logged_in? then nav_link('Log out', logout_path) else nav_link('Log in', login_path) end

app/views/partials/_notice.html.erb
<div id="notice" class="<%= type %>"><%= message %></div>

app/views/tasks/index.html.erb
<h2><%= @task.try(:description) || 'No tasks' %></h2>

<% if @task.try(:comments) %>
  <p><%= @task.comments %>
<% end %>

<% if @task.present? %>
  <p>
    <%= form_tag(complete_task_path(@task)) do %>
      <div class="actions">
        <%= submit_tag('Complete') %>
      </div>
    <% end %>

    <%= form_tag(pass_task_path(@task)) do %>
      <div class="actions">
        <%= submit_tag('Put it off') %>
      </div>
    <% end %>
  </p>
<% end %>

<p><%= link_to('Create a new task', new_task_path) %></p>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <div class="field">
    <%= f.label(:description) %>
    <%= f.text_field(:description) %>
  </div>

  <div class="field">
    <%= f.label(:comments) %>
    <%= f.text_area(:comments) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>